### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by sac10nikam** [MikeSafonov/spring-boot-starter-smpp#10]
Would like to contribute to this library. Send me your email Id. Sorry for adding this message as an issue.

**Comment by MikeSafonov** [comment]
Greetings, @sac10nikam !
You feel free to contribute to this repo. Create PR or create issue for questions or bug reports.

**Comment by MikeSafonov** [comment]
@sac10nikam now this starter available at https://mvnrepository.com and you feel free to use and test it!

**Comment by sac10nikam** [comment]
Thanks
