### ISSUE TITLE
Using transceiver instead of transmitter

### ISSUE THREAD

**Issue by markusdent** [MikeSafonov/spring-boot-starter-smpp#19]
Hello, 
is there a way to always try to bind with TRANSCEIVER, instead of TRANSMITTER and RECEIVER?

**Comment by MikeSafonov** [comment]
Hello.
Unfortunately its not possible at the moment. 
As for me i think it will be good feature. I will try to add this feature.

**Comment by MikeSafonov** [comment]
Hi @markusdent 
Please check [v1.1.0](https://github.com/MikeSafonov/spring-boot-starter-smpp/releases/tag/v1.1.0)

**Comment by markusdent** [comment]
Hey @MikeSafonov,

thank you very much!  I really appreciate your work.
Will check it out soon.
