### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by atkawa7** [MikeSafonov/spring-boot-starter-smpp#82]
Hi. Thank you for creating this library. Just wondering what's the license for this project. It seems its MIT. However the dependencies are AGPL like `org.restcomm.smpp`.

https://mvnrepository.com/artifact/org.restcomm.smpp/ch-commons-util/7.0.6

 Is it possible to move to something like `com.cloudhopper`

**Comment by MikeSafonov** [comment]
Hello, @atkawa7. Thank you for your attention

I will try to use `com.cloudhopper` dependencies in next release.

**Comment by atkawa7** [comment]
@MikeSafonov I might be wrong. Because there is  certainly an apache one here https://github.com/RestComm/cloudhopper-smpp. If the code is based off that then we can keep using it.
